spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tungus
    username: username
    password: password

connect: https://test-fuso.ngnexusccs.xyz/tt

#logging:
#  level.tech.uinb.tungus.service.impl.ScheduleServiceImpl: debug
